services:
  galera-1:
    image: bitnami/mariadb-galera:11.4.3-debian-12-r0
    container_name: dc1-galera-1
    env_file:
      - ../../env/dc1.env
    environment:
      MARIADB_GALERA_CLUSTER_NAME: passbolt-galera
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://dc1-galera-1,dc1-galera-2,dc2-galera-3
      MARIADB_GALERA_NODE_NAME: dc1-galera-1
      MARIADB_GALERA_NODE_ADDRESS: dc1-galera-1
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: passbolt
      MARIADB_USER: passbolt
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../../volumes/db/dc1/galera-1:/bitnami/mariadb
    networks:
      - dc1-net
      - galera-net

  galera-2:
    image: bitnami/mariadb-galera:11.4.3-debian-12-r0
    container_name: dc1-galera-2
    env_file:
      - ../../env/dc1.env
    environment:
      MARIADB_GALERA_CLUSTER_NAME: passbolt-galera
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://dc1-galera-1,dc1-galera-2,dc2-galera-3
      MARIADB_GALERA_NODE_NAME: dc1-galera-2
      MARIADB_GALERA_NODE_ADDRESS: dc1-galera-2
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: passbolt
      MARIADB_USER: passbolt
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../../volumes/db/dc1/galera-2:/bitnami/mariadb
    networks:
      - dc1-net
      - galera-net

networks:
  dc1-net:
    name: dc1-net
    external: true
  galera-net:
    name: galera-net
    external: true
