services:
  traefik:
    image: traefik:v3.6.7
    container_name: dc2-traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
    ports:
      - "8082:80"
      - "8444:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dc2-net

networks:
  dc2-net:
    name: dc2-net
